sudo: required
dist: trusty
language: node_js
node_js:
  - "lts/*"
  - "10"
  - "8"
before_install:
  - source /opt/jdk_switcher/jdk_switcher.sh
  - jdk_switcher use oraclejdk8
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
